Add missing package dependency for trace_link.py
Summary:
Add missing dependency for execution_graph.py
```
$ conda create -n param python=3.8.0
$ conda activate param
$ git clone --recurse-submodules git@github.com:facebookresearch/param.git
$ cd param
$ pip3 install -r requirements.txt
$ cd train/compute/python/
$ pip3 install -r requirements.txt
$ pip3 install .
$ python tools/trace_link.py --et-file <et-file> --kineto-file <kineto-file>
[2023-07-21 11:12:30,500] trace_link.py:90 [INFO]: Number of original ops in execution trace: 11389
[2023-07-21 11:12:30,695] trace_link.py:136 [INFO]: Number of original ops in kineto trace: 9040
[2023-07-21 11:12:30,750] trace_link.py:274 [INFO]: Kineto tree nodes number: 8651
[2023-07-21 11:12:30,783] trace_link.py:278 [INFO]: ET tree nodes number: 11069
[2023-07-21 11:12:30,786] trace_link.py:295 [INFO]: Graphs are not isomorphic
Traceback (most recent call last):
  File "tools/trace_link.py", line 361, in <module>
    et_enhanced_duration = approximate_match(kineto_et_events, et_nodes)
  File "tools/trace_link.py", line 307, in approximate_match
    cost = next(edit_distance_generator)
  File ".../networkx/algorithms/similarity.py", line 505, in optimize_graph_edit_distance
    for _, _, cost in optimize_edit_paths(
  File ".../networkx/algorithms/similarity.py", line 671, in optimize_edit_paths
    import scipy as sp
ModuleNotFoundError: No module named 'scipy'

Reviewed By: briancoutinho

Differential Revision: D47680775

fbshipit-source-id: 97b004744abfc5b34403188bd2ff3ad6330e702a