Fix for dataset parsing error when the 'linear' option is executed in driver.py.
Summary:
Code changes to fix the dataset parsing in the driver.py.  The changes are similar to how pytorch_linear.py handles the dataset parsing.  In addition to parsing code changes fixing certain printing and debug sections of the code.
---------------------------------------
Below error without the code change:
~/fbcode/buck-out/opt/last/driver.par --steps=100 --device='gpu' linear --dataset='A'

Traceback (most recent call last):
  File "/data/home/ashwinrama/repos/param/train/compute/pt/driver.py", line 65, in <module>
    klinear.run(args, dataset.mlp_A)
  File "/data/home/ashwinrama/repos/param/train/compute/pt/pytorch_linear.py", line 316, in run
    layers_size, batch_size = dataset[i]
ValueError: too many values to unpack (expected 2)

Reviewed By: nrsatish, kingchc

Differential Revision: D38606741

fbshipit-source-id: 818bdc4acd94703be4dd396546c5e0f16a2c1a02