fix group_rank with ext_dist
Summary:
When a group is created by extended distribute, we need to query group rank by using the internal pg but not the extended wrapper. Otherwise it reports error below:
```
RuntimeError: Group <caffe2.torch.fb.hpc.extend_distributed.ExtendProcessGroup object at 0x7f1743432a60> is not registered, please create group with torch.distributed.new_group API
```

This patch fixes it.

Reviewed By: wesbland, kingchc

Differential Revision: D45212978

fbshipit-source-id: 4f94b169ddb061f8e0746a2302d5fbafd65147c9