Add missing package dependency for execution_graph.py
Summary:
Add missing dependency for execution_graph.py
```
$ conda create -n param python=3.8.0
$ conda activate param
$ git clone --recurse-submodules git@github.com:facebookresearch/param.git
$ cd param
$ pip3 install -r requirements.txt
$ cd train/compute/python/
$ pip3 install -r requirements.txt
$ pip3 install .
$ cd test/data/
$ gunzip -d *.gz
$ cd -
$ python tools/trace_link.py --et-file test/data/resnet_et.json --kineto-file test/data/resnet_kineto.json --annotation 'enumerate(DataLoader)#_MultiProcessingDataLoaderIter.__next__'
raceback (most recent call last):
  File ".../execution_graph.py", line 16, in <module>
    import pydot
ModuleNotFoundError: No module named 'pydot'
```

Reviewed By: briancoutinho

Differential Revision: D47676828

fbshipit-source-id: adc4e1e0a9dd7abf13295d55f0809ff50cf28b3e