fix unittest import
Summary:
unittests are failing right now

```
⚠ Fatal: param_bench/train/comms/pt:commsTraceReplay_tests - test_tensor_shrink_alltoallv (param_bench.train.comms.pt.tests.commsTraceReplay_tests.TestPrepComms) (9.3s)
Test appears to have passed but the binary exited with a non-zero exit code.
This usually means something has crashed after the test was done.
stdout:

stderr:
/data/users/phenzler/fbsource/buck-out/v2/gen/fbcode/132d6ec84f7266ec/param_bench/train/comms/pt/__commsTraceReplay_tests__/commsTraceReplay_tests#link-tree/torch/_utils_internal.py:282: NCCL_DEBUG env var is set to None
/data/users/phenzler/fbsource/buck-out/v2/gen/fbcode/132d6ec84f7266ec/param_bench/train/comms/pt/__commsTraceReplay_tests__/commsTraceReplay_tests#link-tree/torch/_utils_internal.py:300: NCCL_DEBUG is forced to WARN from None
Failed to import test module: commsTraceReplay_tests
Traceback (most recent call last):
  File "/usr/local/fbcode/platform010/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/data/users/phenzler/fbsource/buck-out/v2/gen/fbcode/132d6ec84f7266ec/param_bench/train/comms/pt/__commsTraceReplay_tests__/commsTraceReplay_tests#link-tree/param_bench/train/comms/pt/tests/commsTraceReplay_tests.py", line 6, in <module>
    from comms_utils import commsArgs
ModuleNotFoundError: No module named 'comms_utils'

exit_code:"Process terminated by the signal: 1"
Buck UI: https://www.internalfb.com/buck2/825131bd-1947-4ace-afef-a56cbd5c4417
Test UI: https://www.internalfb.com/intern/testinfra/testrun/1688850136050808
Network: Up: 863MiB  Down: 4.2GiB  (reSessionID-c771f26d-fd62-4823-a6b7-5e23d0d9f31c)
Loading targets.   Remaining      0/4691
Analyzing targets. Remaining      0/64281
Executing actions. Remaining      0/404777
Command: test.     Finished 5 local, 5578 remote, 102641 cache (95% hit)
Time elapsed: 8:57.2s
Tests finished: Pass 0. Fail 0. Fatal 1. Skip 0. Build failure 0
1 TESTS FATALS
  ⚠ param_bench/train/comms/pt:commsTraceReplay_tests - test_tensor_shrink_alltoallv (param_bench.train.comms.pt.tests.commsTraceReplay_tests.TestPrepComms)
```

Reviewed By: wesbland

Differential Revision: D72036539

fbshipit-source-id: e3e4e48059fda1f23c19fbe23bdc9be64d8c1079