Add missing package dependency for et_replay_utils.py
Summary:
Add missing dependency for et_replay_utils.py
```
$ alias with-proxy='HTTPS_PROXY=http://fwdproxy:8080 HTTP_PROXY=http://fwdproxy:8080 FTP_PROXY=http://fwdproxy:8080 https_proxy=http://fwdproxy:8080 http_proxy=http://fwdproxy:8080 ftp_proxy=http://fwdproxy:8080 http_no_proxy='\''\'\'\''*.facebook.com|*.tfbnw.net|*.fb.com'\''\'\'
$ feature install conda
$ with-proxy conda create -n param python=3.8.0
$ conda activate param
$ cd ~/fbcode/param_bench
$ with-proxy pip3 install -r requirements.txt
$ cd train/comms/pt/
$ with-proxy pip3 install -r requirements.txt
$ pip3 install .
$ cd -
$ cd train/compute/python/
$ with-proxy pip3 install -r requirements.txt
$ pip3 install .
$ python3 -m tools.et_replay
Traceback (most recent call last):
  File ".../et_replay_utils.py", line 4, in <module>
    from fbgemm_gpu.split_table_batched_embeddings_ops import PoolingMode, WeightDecayMode
ModuleNotFoundError: No module named 'fbgemm_gpu'
```

Reviewed By: fengxizhou

Differential Revision: D47991303

fbshipit-source-id: 7d8489149732ea689e9cea461149a8b53d250f28