initialize_groups: Fix backend overwriting processGroup attribute 2.0
Summary:
Follow-up from D65796833. Forgot about some other call sites for initialize_groups

From previous diff:
------------------------------
I have noticed `processGroup` attribute was being overwritten by the `backend`. Fixed by making sure we set the right attribute  in the call from `genMultiCommGroups`
This was causing the following error:
```
ace#link-tree/param_bench/train/comms/pt/pytorch_dist_backend.py", line 1175, in initialize_groups
[rank0]:     for pg_id, group_ranks in self.groupRanks.items():
[rank0]: AttributeError: 'str' object has no attribute 'items'
``

Reviewed By: kingchc

Differential Revision: D65800353

fbshipit-source-id: 00ad4403d5bbd034fe7f8294eb3029e49c51f59b